### ISSUE TITLE
HTTP Connection Error on running client.py

### ISSUE THREAD

**Issue by ghost** [hu-ner/huner#2]
I followed the steps outlined in the readme to annotate a sample text file:

```
./start_server.sh gene_all
python3 client.py test.txt output.conll --name gene_all
```

The docker container is created and the server runs, but on running client.py I get the HTTP Connection error:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.17.0.2', port=5000): Max retries exceeded with url: /tag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088b5750>: Failed to establish a new connection: [Errno 60] Operation timed out'))`

Here is my system info:

OS: Mac OS Catalina 10.15.1
Running zsh shell
Docker version 19.03.5, build 633a0ea

Any help would be appreciated!

**Comment by yetinam** [comment]
Thanks for reporting the issue.

We managed to reproduce the issue. It is related to differences in local networking with Docker for Linux and Mac. As on Mac Docker is started inside a VM, our current script is not able to connect to the annotation server. We will fix the issue in the next days.

**Comment by leonweber** [comment]
Hey @gnakum. Thanks for reporting this issue! It should be fixed on the branch https://github.com/hu-ner/huner/tree/fix_macos_networking . It would be great if you could verify that this resolves your issue.

**Comment by ghost** [comment]
I cloned the fix_macos_networking branch, but this time on running start_server, I get:

```
apple@Apples-MacBook-Pro huner % ./start_server.sh chemical_all
Using default tag: latest
latest: Pulling from huner/huner
Digest: sha256:4b7b780fac06b21258cab7d1d54ae5284b7e6fcc53cedbfe57fa35ee1aaeb6e8
Status: Image is up to date for huner/huner:latest
docker.io/huner/huner:latest
Compiling...
 * Serving Flask app "tagger" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Compiling...
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method _NonClosingTextIOWrapper.__del__ of <_io.TextIOWrapper encoding='utf-8'>> [ignored[](url)](url)
```

**Comment by leonweber** [comment]
Hey @gnakum thanks for reporting back! I will have a look into this on Monday.

**Comment by leonweber** [comment]
Hey @gnakum. Unfortunately, I cannot reproduce on the latest macOS Catalina (10.15.1):

```bash
(base) ~/Downloads ❯❯❯ git clone git@github.com:hu-ner/huner.git
Cloning into 'huner'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 196 (delta 1), reused 1 (delta 0), pack-reused 189
Receiving objects: 100% (196/196), 340.95 KiB | 1011.00 KiB/s, done.
Resolving deltas: 100% (45/45), done.
(base) ~/Downloads ❯❯❯ git checkout fix
(base) ~/Downloads ❯❯❯ cd huner                                          ✘ 130
(base) ~/D/huner ❯❯❯ git checkout fix_macos_networking
Branch 'fix_macos_networking' set up to track remote branch 'fix_macos_networking' from 'origin'.
Switched to a new branch 'fix_macos_networking'
(base) ~/D/huner ❯❯❯ cp -r ~/projects/huner/models/cellline_all models
(base) ~/D/huner ❯❯❯ ./start_server.sh cellline_all
Using default tag: latest
latest: Pulling from huner/huner
Digest: sha256:4b7b780fac06b21258cab7d1d54ae5284b7e6fcc53cedbfe57fa35ee1aaeb6e8
Status: Image is up to date for huner/huner:latest
docker.io/huner/huner:latest
Compiling...
 * Serving Flask app "tagger" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Compiling...
 * Debugger is active!
 * Debugger PIN: 236-035-556
```

From a different terminal:
```bash
python client.py --name cellline_all ~/projects/huner/test.txt test.conll
```

Results in:
```bash
172.17.0.1 - - [10/Dec/2019 16:41:50] "POST /tag HTTP/1.1" 200 -
```

I am on Docker Desktop 2.1.0.5

Did you do exactly the same?

**Comment by ghost** [comment]
Hi, yes I did exactly the same and I got it working for the cellline_all model. However, it still does not work for  chemical_all or gene_all models. My corpus consists of articles which have mostly chemical/gene entities. Could you please see if the images for these two models are up-to-date? Thanks!

And yes, the client.py also works for cellline_all.

I am also on Docker Desktop 2.1.0.5, macOS Catalina

**Comment by leonweber** [comment]
Hey, thanks for following up. I can reproduce the issue with chemical_all on MacOS but not on Linux I suspect that it has to do with UTF8 encoding, because if I recall correctly, the chemical model had some unusual characters in its vocabulary. I will look into this.

**Comment by leonweber** [comment]
Hey @gnakum . I have pushed a new commit on https://github.com/hu-ner/huner/tree/fix_macos_networking which fixes the issue for me. It would be great, if you could check if this also fixes your issue.

**Comment by ghost** [comment]
Hey @leonweber I ran the gene_all and chemical_all models using the latest commit and everything seems to be working well. Many thanks for all your help! 

I am just curious what was the issue earlier. If you could provide a brief explanation, it would be great.
